import en from "./en.json";

/* The English dictionary is the source of truth. Every other language is a
 * machine-translated copy of this exact shape, generated by scripts/translate.mjs
 * into ./generated/<code>.json. `Dictionary` is derived from the English JSON so
 * the whole app stays type-checked against one canonical structure. */
export type Dictionary = typeof en;

export const enDictionary: Dictionary = en;

/* Generated translation files may be partial (a language can be translated
 * incrementally). Deep-merge the loaded translation over English so any missing
 * key — or an entirely missing branch — transparently falls back to English. */
export function mergeDictionary(base: Dictionary, override: unknown): Dictionary {
  return deepMerge(base, override) as Dictionary;
}

function deepMerge<T>(base: T, override: unknown): T {
  if (override === null || override === undefined) return base;

  if (Array.isArray(base)) {
    if (!Array.isArray(override)) return base;
    return base.map((item, i) =>
      i < override.length ? deepMerge(item, override[i]) : item
    ) as unknown as T;
  }

  if (typeof base === "object") {
    if (typeof override !== "object" || Array.isArray(override)) return base;
    const out: Record<string, unknown> = { ...(base as Record<string, unknown>) };
    for (const key of Object.keys(base as Record<string, unknown>)) {
      out[key] = deepMerge(
        (base as Record<string, unknown>)[key],
        (override as Record<string, unknown>)[key]
      );
    }
    return out as T;
  }

  /* Leaf: prefer the translated string only when it's a non-empty string. */
  return typeof override === "string" && override.length > 0
    ? (override as unknown as T)
    : base;
}
